In [1]:
import pandas as pd

perguntas = pd.read_csv('stackoverflow_perguntas.csv')
perguntas.head()

Perguntas           Tags
0  Possuo um projeto Node.js porém preciso criar ...        node.js
1  Gostaria de fazer testes unitários no Node.js,...        node.js
2  Como inverter a ordem com que o jQuery itera u...         jquery
3  Eu tenho uma página onde pretendo utilizar um ...           html
4  Como exibir os dados retornados do FireStore e...  html angular

## Classificação Multiclasse

Pensando em Avenida Brasil, Star Wars e Friends, cada um só pode ser colocado um uma classe: Novela, Filme ou Série.
<br> Ou seja, não é possível estar presente em mais de uma classe.

## Classificação Multilabel

Pensando em Star Wars, o filme tem mais de um gênero: Fantasia, Aventura e Ação, por exemplo.
<br> Ou seja, pode apresentar mais de um label, que é o que acontece com as tags nas perguntas do stackoverflow.

# Usar Strings como Target

In [2]:
perguntas.shape

(5408, 2)

In [3]:
len(perguntas.Tags.unique())

37

In [4]:
perguntas.Tags.unique()

array(['node.js', 'jquery', 'html', 'html angular ', 'html ', 'angular',
       'angular ', 'jquery html  ', 'jquery ', 'jquery html',
       'jquery html ', 'html angular', 'angular node.js ', 'html  ',
       'jquery html angular', 'node.js ', 'html jquery', 'html jquery ',
       'jquery angular  ', 'html node.js', 'jquery  ', 'angular node.js',
       'jquery angular', 'html node.js ', 'jquery node.js ', 'angular  ',
       'jquery angular ', 'jquery html angular ', 'node.js html ',
       ' node.js', 'node.js html', 'html angular  ', 'jquery node.js',
       'angular html', 'html angular  node.js', 'jquery html node.js',
       'html angular node.js'], dtype=object)

### Tratamentos necessários

1. strings semelhantes 'html' e 'html '
2. ordem de palavras diferentes

In [5]:
label = list()

for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in label:
            label.append(tag)
print(label)

['node.js', 'jquery', 'html', 'angular']


In [6]:
node_js = list()

for linha_tag in perguntas.Tags:
    if "node.js" in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)
node_js

[1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,


In [7]:
perguntas['node.js'] = node_js

In [8]:
perguntas.head()

Perguntas           Tags  node.js
0  Possuo um projeto Node.js porém preciso criar ...        node.js        1
1  Gostaria de fazer testes unitários no Node.js,...        node.js        1
2  Como inverter a ordem com que o jQuery itera u...         jquery        0
3  Eu tenho uma página onde pretendo utilizar um ...           html        0
4  Como exibir os dados retornados do FireStore e...  html angular         0

In [9]:
def nova_coluna(lista_tags, dataframe, nome_tags):

    for tag in label:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)
        dataframe[tag] = coluna

In [10]:
nova_coluna(label, perguntas, 'Tags')
perguntas.head(10)

Perguntas           Tags  node.js  \
0  Possuo um projeto Node.js porém preciso criar ...        node.js        1   
1  Gostaria de fazer testes unitários no Node.js,...        node.js        1   
2  Como inverter a ordem com que o jQuery itera u...         jquery        0   
3  Eu tenho uma página onde pretendo utilizar um ...           html        0   
4  Como exibir os dados retornados do FireStore e...  html angular         0   
5  Vi esse vídeo (link abaixo) e gostaria de cons...          html         0   
6  Eu consigo fazer uma requisição de upload de u...        angular        0   
7  Está apresentando o seguinte erro:  'ionic' nã...        node.js        1   
8  Tenho um formulário reativo e eu preciso mostr...        angular        0   
9  Eu estou com esse problema e não faço ideia de...        node.js        1   

   jquery  html  angular  
0       0     0        0  
1       0     0        0  
2       1     0        0  
3       0     1        0  
4       0     1        1  
5       0     1        0  
6       0     0        1  
7       0     0        0  
8       0     0        1  
9       0     0        0

In [11]:
# juntando as colunas de classificação - ZIP
# juntar elemento 1 da lista 1 com a 2, e elemento 2 da lista 1 com o da lista 2
# zip retorna uma lista de tuplas

lista_1 = [1, 2]
lista_2 = [5, 4]
lista_zip = zip(lista_1, lista_2)
print(list(lista_zip))

[(1, 5), (2, 4)]


In [12]:
lista_zip_tags = list(zip(perguntas['node.js'],
                     perguntas.jquery,
                     perguntas.html,
                     perguntas.angular
                     ))

perguntas['todas_tags'] = lista_zip_tags
perguntas.head(10)

# poderia usar perguntas[label[0]] e assim por diante

Perguntas           Tags  node.js  \
0  Possuo um projeto Node.js porém preciso criar ...        node.js        1   
1  Gostaria de fazer testes unitários no Node.js,...        node.js        1   
2  Como inverter a ordem com que o jQuery itera u...         jquery        0   
3  Eu tenho uma página onde pretendo utilizar um ...           html        0   
4  Como exibir os dados retornados do FireStore e...  html angular         0   
5  Vi esse vídeo (link abaixo) e gostaria de cons...          html         0   
6  Eu consigo fazer uma requisição de upload de u...        angular        0   
7  Está apresentando o seguinte erro:  'ionic' nã...        node.js        1   
8  Tenho um formulário reativo e eu preciso mostr...        angular        0   
9  Eu estou com esse problema e não faço ideia de...        node.js        1   

   jquery  html  angular    todas_tags  
0       0     0        0  (1, 0, 0, 0)  
1       0     0        0  (1, 0, 0, 0)  
2       1     0        0  (0, 1, 0, 0)  
3       0     1        0  (0, 0, 1, 0)  
4       0     1        1  (0, 0, 1, 1)  
5       0     1        0  (0, 0, 1, 0)  
6       0     0        1  (0, 0, 0, 1)  
7       0     0        0  (1, 0, 0, 0)  
8       0     0        1  (0, 0, 0, 1)  
9       0     0        0  (1, 0, 0, 0)

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

X = perguntas.Perguntas
y = perguntas.todas_tags

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 123, test_size = 0.2)

tf_idf = TfidfVectorizer(max_features = 5000,
                         max_df = 0.85) # max_features limita quantas palavras estão no vocabulário

vetor_tfidf = tf_idf.fit(X)
X_train_tfidf = vetor_tfidf.transform(X_train)
X_test_tfidf = vetor_tfidf.transform(X_test)

print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [14]:
print(type(y_train))

<class 'pandas.core.series.Series'>


In [15]:
from sklearn.multiclass import OneVsRestClassifier
import numpy as np

y_train_array = np.asarray(list(y_train))
y_test_array = np.asarray(list(y_test))

print(y_train_array) # ainda é um array de tuplas, preciso transformar em uma lista, adiciono o list() no np.asarray


[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]


In [16]:
regressao_logistica = LogisticRegression(solver = 'lbfgs')
classificador_OvR = OneVsRestClassifier(regressao_logistica)
classificador_OvR.fit(X_train_tfidf, y_train_array)
accuracy_OvR = classificador_OvR.score(X_test_tfidf, y_test_array)
print('A acurácio do modelo é:{0: .2f}%'.format(accuracy_OvR*100))

A acurácio do modelo é: 41.68%


In [17]:
perguntas.todas_tags.unique()

array([(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1),
       (0, 0, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 1, 1),
       (0, 1, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 1, 1),
       (1, 1, 1, 0)], dtype=object)

In [18]:
len(perguntas.todas_tags.unique())

13

## Exact math e Hamming Loss

Não é a métrica ideal porque ele olha a linha como um todo e o ideal é olhar cada célula da linha.

real = [
    (1, 1, 1, 0),
    (0, 1, 1, 0),
    (0, 1, 1, 1)
]

previsto = [
    (1, 1, 1, 0),
    (0, 0, 1, 0),
    (1, 1, 1, 0)
]

Usamos então a <b> Hamming Loss </b>: ela calcula a distância do valor previsto ao valor real e nos permite olhar cada célula

previsto = [
    0,
    1,
    2
] # quantidade de erros do modelo nas células

Hamming loss = distância total (3) / quantidade de células (12)

In [19]:
from sklearn.metrics import hamming_loss

previsto_OvR = classificador_OvR.predict(X_test_tfidf)
hamming_loss_OvR = hamming_loss(y_test_array, previsto_OvR)

print('Hamming Loss:{0: .2f}'.format(hamming_loss_OvR))

# Quanto mais próximo de zero, melhor.

Hamming Loss: 0.19


In [20]:
perguntas.head()

Perguntas           Tags  node.js  \
0  Possuo um projeto Node.js porém preciso criar ...        node.js        1   
1  Gostaria de fazer testes unitários no Node.js,...        node.js        1   
2  Como inverter a ordem com que o jQuery itera u...         jquery        0   
3  Eu tenho uma página onde pretendo utilizar um ...           html        0   
4  Como exibir os dados retornados do FireStore e...  html angular         0   

   jquery  html  angular    todas_tags  
0       0     0        0  (1, 0, 0, 0)  
1       0     0        0  (1, 0, 0, 0)  
2       1     0        0  (0, 1, 0, 0)  
3       0     1        0  (0, 0, 1, 0)  
4       0     1        1  (0, 0, 1, 1)

In [21]:
perguntas[['node.js', 'jquery', 'html', 'angular']].corr()

node.js    jquery      html   angular
node.js  1.000000 -0.321485 -0.273523 -0.101787
jquery  -0.321485  1.000000 -0.253977 -0.366269
html    -0.273523 -0.253977  1.000000 -0.286706
angular -0.101787 -0.366269 -0.286706  1.000000

# Classificação em cadeia

A construção da base de treinamento é diferente.
As colunas vão sendo carregadas. Na primeira coluna, a entrada são as perguntas. A segunda coluna tem como entrada as perguntas + coluna 1 e assim sucessivamente.

In [22]:
!pip install scikit-multilearn==0.2.0


[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
from skmultilearn.problem_transform import ClassifierChain

classificador_chain = ClassifierChain(regressao_logistica)
classificador_chain.fit(X_train_tfidf, y_train_array)
score_chain = classificador_chain.score(X_test_tfidf, y_test_array)
previsto_cadeia = classificador_chain.predict(X_test_tfidf)
hamming_loss_chain = hamming_loss(y_test_array, previsto_cadeia)

print('A acurácio do modelo é:{0: .2f}%'.format(score_chain*100))
print('Hamming Loss:{0: .2f}'.format(hamming_loss_chain))

A acurácio do modelo é: 49.82%
Hamming Loss: 0.21


In [24]:
from skmultilearn.problem_transform import BinaryRelevance

classificador_br = BinaryRelevance(regressao_logistica)
classificador_br.fit(X_train_tfidf, y_train_array)
score_br = classificador_br.score(X_test_tfidf, y_test_array)
previsto_br = classificador_br.predict(X_test_tfidf)
hamming_loss_br = hamming_loss(y_test_array, previsto_br)

print('A acurácio do modelo é:{0: .2f}%'.format(score_br*100))
print('Hamming Loss:{0: .2f}'.format(hamming_loss_br))

A acurácio do modelo é: 41.68%
Hamming Loss: 0.19


In [25]:
from skmultilearn.adapt import MLkNN


classificador_mlknn = MLkNN() # não preciso mais usar os parãmetros de outro classificador regressao_logistica
classificador_mlknn.fit(X_train_tfidf, y_train_array)
score_mlknn = classificador_mlknn.score(X_test_tfidf, y_test_array)
previsto_mlknn = classificador_mlknn.predict(X_test_tfidf)
hamming_loss_mlknn = hamming_loss(y_test_array, previsto_mlknn)

print('A acurácio do modelo é:{0: .2f}%'.format(score_mlknn*100))
print('Hamming Loss:{0: .2f}'.format(hamming_loss_mlknn))

A acurácio do modelo é: 34.10%
Hamming Loss: 0.25


In [26]:
print('A acurácia do MLkNN é:{0: .2f}%'.format(score_mlknn*100))
print('Hamming Loss:{0: .2f}'.format(hamming_loss_mlknn))
print('---------------------------------------------')
print('A acurácia da BinaryRelevance é:{0: .2f}%'.format(score_br*100))
print('Hamming Loss:{0: .2f}'.format(hamming_loss_br))
print('---------------------------------------------')
print('A acurácia do Chain é:{0: .2f}%'.format(score_chain*100))
print('Hamming Loss:{0: .2f}'.format(hamming_loss_chain))

A acurácia do MLkNN é: 34.10%
Hamming Loss: 0.25
---------------------------------------------
A acurácia da BinaryRelevance é: 41.68%
Hamming Loss: 0.19
---------------------------------------------
A acurácia do Chain é: 49.82%
Hamming Loss: 0.21


In [29]:
resultados_classificacao = pd.DataFrame()
resultados_classificacao['perguntas'] = X_test.values # para inicializar o index e não puxar do perguntas
resultados_classificacao['tags real'] = list(y_test)
resultados_classificacao['BR'] = list(previsto_br.toarray()) # como era uma lista esparsa, preciso transformar numa lista primeiro
resultados_classificacao['cadeia'] = list(previsto_cadeia.toarray())
resultados_classificacao['MLkNN'] = list(previsto_mlknn.toarray())

In [30]:
resultados_classificacao.head()

perguntas     tags real  \
0  estou com conflito entre o  CODE   e os  CODE ...  (0, 1, 0, 0)   
1  Estou fazendo um site que eu sou obrigado a us...  (0, 0, 1, 0)   
2  Recentemente fiz um refactor do meu código par...  (1, 0, 0, 0)   
3  Eu tenho esse código em CODE  que passo valore...  (0, 1, 1, 0)   
4  Olá, em minha função tem o evento CODE  que de...  (0, 1, 1, 0)   

             BR                cadeia         MLkNN  
0  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 0, 0]  
1  [0, 0, 1, 0]  [0.0, 0.0, 1.0, 0.0]  [0, 1, 1, 0]  
2  [1, 0, 0, 0]  [1.0, 0.0, 0.0, 0.0]  [1, 0, 0, 0]  
3  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 0, 1, 0]  
4  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 1, 0]

In [32]:
resultados_classificacao.iloc[1]

perguntas    Estou fazendo um site que eu sou obrigado a us...
tags real                                         (0, 0, 1, 0)
BR                                                [0, 0, 1, 0]
cadeia                                    [0.0, 0.0, 1.0, 0.0]
MLkNN                                             [0, 1, 1, 0]
Name: 1, dtype: object

In [33]:
resultados_classificacao.perguntas[1]

'Estou fazendo um site que eu sou obrigado a usar HTML, CSS e JavaScript no máximo. Só que muitas coisas que eu preciso do PhP eu não posso usar. Sendo assim eu estive pesquisando por sinonimo de CODE  e encontrei o seguinte, que ajudou em partes:  CODE   Tá, mas qual é o problema? Ele cria uma barra de rolagem do lado. Eu sei como remover com CSS, mas o texto que foi inserido rola só dentro da área da CODE  e eu queria que fizesse como se o texto inserido fizesse parte da página, como funciona no CODE  do PhP. A questão é, como fazer a mecânica do JavaScript nesse caso ficar igual ao do PhP?  Print para exemplificar: https://imgur.com/a/V9AGLgB '